# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

product_controllers:
    resource:
        path: ../src/Product/Presentation/Http/Controller/
        namespace: App\Product\Presentation\Http\Controller
    type: attribute

user_controllers:
    resource:
        path: ../src/User/Presentation/Http/Controller/
        namespace: App\User\Presentation\Http\Controller
    type: attribute
